# Generated by Django 4.0 on 2022-01-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsdata',
            name='Avg',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentsdata',
            name='Total',
            field=models.IntegerField(null=True),
        ),
    ]
